### ISSUE TITLE
Build a web API

### ISSUE THREAD

**Issue by greysteil** [dependabot/elixir-security-advisories#3]
GitHub is a great place to store the data for security advisories, and pull requests/commits are a relatively good flow for creating new advisories. However, a database of YAML files isn't the easiest thing in the world to query!

We should build a web API that pulls in the data from here and serves it over HTTP. Ideally that service would also allow integrators to sign up for webhooks, so they're alerted as soon as a new vulnerability is disclosed.

Note: the code for this API probably *shouldn't* live in this repo. Integrators who are pulling data directly from this repo are almost certainly polling it to check what the latest commit is, and triggering a refresh of their data based on that. If we build a full-blown application in the repo we'll create lots of unnecessary noise for them.

**Comment by maennchen** [comment]
I'm currently working on a little side project to help build this one. I'll soon share a repo as a base of discussion.

**Comment by maennchen** [comment]
@greysteil I published a first WIP of the API here: https://github.com/ex-security-advisory/api/tree/v1

This probably contains a lot of bugs, is not stable and has currently not a single test. It should be sufficient for a discussing, however.

The API provides a REST and a GraphQL interface.

Please have a look and tell me what you think here: https://github.com/ex-security-advisory/api/issues/1

**Comment by greysteil** [comment]
Have added a link across from the readme, and I'm going to close this to avoid confusion. Will pick up discussion over on your repo. 🙂
