### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by batarian71** [dependabot/elixir-security-advisories#4]
Hi,

Can I design a logo for your application? In my free time I contribute to open source softwares. If you give me your approval, I will design a logo for you. 

Best regards.

**Comment by greysteil** [comment]
Yes please - that would be fab! Something about Elixir and security would be 🔥

**Comment by batarian71** [comment]
Hi again, ofcourse!

i designed a logo. Did you like it?

![esa](https://user-images.githubusercontent.com/36008612/40570917-a5d97276-6098-11e8-8af8-27661dc5f869.jpg)

**Comment by greysteil** [comment]
This is rad, I love it! Can I make a suggestion on the text, though? I think a font that looks more "serious" might be good.

Ping me a vector copy (support@dependabot.com) or put in a PR to add it to the readme, crediting yourself at the bottom.

Thanks @batarian71!

**Comment by batarian71** [comment]
I changed the font. How is this?

![esa](https://user-images.githubusercontent.com/36008612/40577096-8c022846-6108-11e8-93d8-af165d52e470.jpg)

I will send a pr. Which version should I load into the readme file? (vertical-horizontal-only logo version)

**Comment by batarian71** [comment]
Thank you :) Can you check it?

https://github.com/dependabot/elixir-security-advisories/pull/5

**Comment by greysteil** [comment]
Epic, loving your work!

**Comment by greysteil** [comment]
It's a really nice logo. Thanks so much!
